from flask import Flask, request, jsonify
from flask_cors import CORS
import joblib
import requests
from datetime import datetime

app = Flask(__name__)
CORS(app) # Allows your GitHub Pages frontend to talk to this backend

# Load the trained ML model generated by train_model.py
try:
    model = joblib.load('pookify_smart_model.pkl')
except FileNotFoundError:
    print("Error: Run train_model.py first to generate the model.")

def get_weather_code(lat, lon):
    """
    Fetches real-time weather. 
    Requires a free API key from openweathermap.org
    """
    return 1 # Returning a mock weather code (1 = Clouds) for this prototype

# --- 1. Your Python Music Database ---
# Replace the audio_url and cover paths with the actual locations of your files!
all_my_songs = [
    {
        "id": "trk_1", 
        "title": "Tum se hi", 
        "audio_url": "https://res.cloudinary.com/dg62tcmhx/video/upload/Tum_Se_Hi_-_Jab_We_Met.mp3", 
        "cover": "https://res.cloudinary.com/dg62tcmhx/image/upload/cover_l3afdf.jpg",
        "bpm": 95 ,
        "weather_tag": "Rain" # Slower, moody vibe for rainy weather       

    },
    {
        "id": "trk_2", 
        "title": "Aa Jao Meri Tamanna", 
        "audio_url": "https://res.cloudinary.com/dg62tcmhx/video/upload/Aa_Jao_Meri_Tamanna_-_Javed_Ali_Jojo_MpThree.in.mp3",
        "cover": "https://res.cloudinary.com/dg62tcmhx/image/upload/cover_l3afdf.jpg",
        "bpm": 105, # Slower, daytime chill vibe
        "weather_tag": "Clouds"
        
    },
    {
        "id": "trk_3",
        "title": "Neele Neele Ambar Par",
        "audio_url": "https://res.cloudinary.com/dg62tcmhx/video/upload/v1776801700/Neele_Neele_Ambar_Par_Male_Version_KoshalWorld.Com.mp3",
        "cover": "https://res.cloudinary.com/dg62tcmhx/image/upload/v1776795596/cover_i2bdjr.jpg",
        "bpm": 115,
        "weather_tag": "Clear" 

    },
    {
        "id": "trk_4", 
        "title": "Lut le gaya", 
        "audio_url": "https://res.cloudinary.com/dg62tcmhx/video/upload/v1776801673/Lutt_Le_Gaya.mp3",
        "cover": "https://res.cloudinary.com/dg62tcmhx/image/upload/v1776795596/cover_i2bdjr.jpg",
        "bpm": 130,
        "weather_tag": "Night"
        
    }
    
    
]

@app.route('/api/smart-mix', methods=['POST'])
def generate_smart_mix():
    data = request.json
    
    # Get user coordinates, with a fallback to a default location
    user_lat = data.get('lat', 28.66) 
    user_lon = data.get('lon', 77.45)
    
    current_hour = datetime.now().hour
    weather_code = get_weather_code(user_lat, user_lon)

    # 1. Make the Prediction
    prediction = model.predict([[current_hour, weather_code]])
    target_bpm, target_energy = prediction[0]

    # 2. Filter the Database for the Perfect Vibe
    matched_tracks = []
    
    for song in all_my_songs:
        # Check if the song's BPM is close to what the ML model wants right now
        bpm_difference = abs(song['bpm'] - target_bpm)
        
        if bpm_difference <= 15: # If it's within 15 BPM, add it to the mix!
            matched_tracks.append(song)
            
    # 3. Fallback Safety
    # If no songs match perfectly, just send the whole library
    if len(matched_tracks) == 0:
        matched_tracks = all_my_songs

    # 4. Return the custom payload to the frontend
    return jsonify({
        "status": "success",
        "context": {"hour": current_hour, "weather_code": weather_code},
        "targets": {"ideal_bpm": round(target_bpm, 2), "ideal_energy": round(target_energy, 2)},
        "playlist": matched_tracks
    })

if __name__ == '__main__':
    app.run(debug=True, port=5000)